---
name: CI

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: elixir:1.14-alpine
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apk add --update bash openssl git build-base
          mix local.hex --force && mix local.rebar --force
          mix deps.get

      - name: Run linters and tests
        env:
          MIX_ENV: test
        run: mix ci
